//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliMed.Persistencia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A32723_CLIMEDEntities : DbContext
    {
        public DB_A32723_CLIMEDEntities()
            : base("name=DB_A32723_CLIMEDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_AGENDA> TB_AGENDA { get; set; }
        public virtual DbSet<TB_ATENDIMENTO> TB_ATENDIMENTO { get; set; }
        public virtual DbSet<TB_PACIENTE> TB_PACIENTE { get; set; }
        public virtual DbSet<TB_PERFIL> TB_PERFIL { get; set; }
        public virtual DbSet<TB_SITUACAO_AGENDA> TB_SITUACAO_AGENDA { get; set; }
        public virtual DbSet<TB_TIPO_SERVICO> TB_TIPO_SERVICO { get; set; }
        public virtual DbSet<TB_USUARIO> TB_USUARIO { get; set; }
    }
}
