//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliMed.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AGENDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_AGENDA()
        {
            this.TB_ATENDIMENTO = new HashSet<TB_ATENDIMENTO>();
        }
    
        public int CD_AGENDA { get; set; }
        public int CD_PACIENTE { get; set; }
        public int CD_TIPO_SERVICO { get; set; }
        public int CD_USUARIO { get; set; }
        public byte CD_SITUACAO_AGENDA { get; set; }
        public System.DateTime DT_DATA { get; set; }
        public string DS_OBSERVACAO { get; set; }
        public Nullable<decimal> VL_VALOR { get; set; }
    
        public virtual TB_PACIENTE TB_PACIENTE { get; set; }
        public virtual TB_SITUACAO_AGENDA TB_SITUACAO_AGENDA { get; set; }
        public virtual TB_TIPO_SERVICO TB_TIPO_SERVICO { get; set; }
        public virtual TB_USUARIO TB_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ATENDIMENTO> TB_ATENDIMENTO { get; set; }
    }
}
