//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliMed.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ATENDIMENTO
    {
        public int CD_ATENDIMENTO { get; set; }
        public int CD_AGENDA { get; set; }
        public int CD_USUARIO { get; set; }
        public System.DateTime DT_DATA { get; set; }
        public string DS_DOENCA { get; set; }
        public string DS_MEDICAMENTOS { get; set; }
    
        public virtual TB_AGENDA TB_AGENDA { get; set; }
        public virtual TB_USUARIO TB_USUARIO { get; set; }
    }
}
