//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliMed.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SITUACAO_AGENDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_SITUACAO_AGENDA()
        {
            this.TB_AGENDA = new HashSet<TB_AGENDA>();
        }
    
        public byte CD_SITUACAO_AGENDA { get; set; }
        public string NM_SITUACAO_AGENDA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_AGENDA> TB_AGENDA { get; set; }
    }
}
